"""Ringdown reproduction package."""

from .compare import (
    align_time_and_phase_by_window,
    interp_complex,
    phase_align_to_reference_at_tref,
    window_waveform,
)
from .conventions import (
    FACE_ON_PLUS_FACTOR_22,
    MPC_METERS,
    MSUN_METERS,
    MSUN_SEC,
    PAPER_FIG10_CONVENTIONS,
    PhysicalConventions,
    detector_real_plus_from_mode22_face_on,
    finite_duration_from_uniform_time_samples,
    paper_fig10_convention_summary,
)
from .experiments import (
    DiagnosticsWriter,
    ExperimentConfig,
    ExperimentPaths,
    PAPER_FIG10_DYNESTY_SHORT,
    PAPER_FIG10_N0_ANCHOR,
    PAPER_FIG10_N3_LOGREL_RELPHASE,
    PAPER_FIG10_PROFILE_GEOMETRY,
    PAPER_FIG10_REGISTRY,
    PaperFigure10ExperimentSpec,
    SamplerConfig,
    paper_fig10_forward_snapshot,
    paper_fig10_registry_markdown,
    run_registered_paper_fig10_script,
    write_paper_fig10_registry_snapshot,
)
from .fit import LinearFitResult, build_design_matrix, solve_complex_lstsq
from .fd_likelihood import (
    FrequencyDomainRingdownLikelihood,
    aligo_zero_det_high_power_psd,
    continuous_ft_from_time_series,
    draw_colored_noise_rfft,
    one_sided_inner_product,
    optimal_snr,
    rfft_continuous,
)
from .frequencies import kerr_qnm_omega_lmn, kerr_qnm_omegas_22n, make_omega_provider_22
from .io import load_waveform_csv, load_waveform_npz
from .metrics import inner_product, mismatch, remnant_error_epsilon
from .preprocess import (
    align_to_peak,
    build_start_time_grid,
    crop_time,
    peak_time_from_strain,
    resample_uniform,
    shift_time,
)
from .scan import (
    NumericalGuardrails,
    PhysicsHeuristics,
    RemnantGridResult,
    StartTimeFitResult,
    fit_at_start_time,
    grid_search_remnant,
    scan_start_times_fixed_omegas,
)
from .sxs_io import SXSRemnantInfo, load_sxs_waveform22
from .types import Waveform22

__all__ = [
    "LinearFitResult",
    "FrequencyDomainRingdownLikelihood",
    "PhysicalConventions",
    "PAPER_FIG10_CONVENTIONS",
    "MSUN_SEC",
    "MSUN_METERS",
    "MPC_METERS",
    "FACE_ON_PLUS_FACTOR_22",
    "detector_real_plus_from_mode22_face_on",
    "finite_duration_from_uniform_time_samples",
    "paper_fig10_convention_summary",
    "ExperimentConfig",
    "SamplerConfig",
    "ExperimentPaths",
    "DiagnosticsWriter",
    "PaperFigure10ExperimentSpec",
    "PAPER_FIG10_DYNESTY_SHORT",
    "PAPER_FIG10_N0_ANCHOR",
    "PAPER_FIG10_PROFILE_GEOMETRY",
    "PAPER_FIG10_N3_LOGREL_RELPHASE",
    "PAPER_FIG10_REGISTRY",
    "paper_fig10_registry_markdown",
    "paper_fig10_forward_snapshot",
    "run_registered_paper_fig10_script",
    "write_paper_fig10_registry_snapshot",
    "NumericalGuardrails",
    "PhysicsHeuristics",
    "RemnantGridResult",
    "SXSRemnantInfo",
    "StartTimeFitResult",
    "Waveform22",
    "align_time_and_phase_by_window",
    "align_to_peak",
    "build_design_matrix",
    "build_start_time_grid",
    "crop_time",
    "fit_at_start_time",
    "grid_search_remnant",
    "interp_complex",
    "inner_product",
    "kerr_qnm_omega_lmn",
    "kerr_qnm_omegas_22n",
    "load_waveform_csv",
    "load_waveform_npz",
    "load_sxs_waveform22",
    "make_omega_provider_22",
    "mismatch",
    "peak_time_from_strain",
    "phase_align_to_reference_at_tref",
    "remnant_error_epsilon",
    "resample_uniform",
    "scan_start_times_fixed_omegas",
    "shift_time",
    "solve_complex_lstsq",
    "aligo_zero_det_high_power_psd",
    "continuous_ft_from_time_series",
    "draw_colored_noise_rfft",
    "one_sided_inner_product",
    "optimal_snr",
    "rfft_continuous",
    "window_waveform",
]
